// Root store
export const RESET_SIDEBAR_STATE = 'resetSidebarState'
export const RESET_MODAL_STATE = 'resetModalState'
export const DISPLAY_MOBILE_SIDEBAR = 'displayMobileSidebar'
export const DISPLAY_RESERVATION_MODAL = 'displayReservationModal'

// Booking module
export const GET_BOOKING_RESULT = 'getBookingResult'
export const CANCEL_CHECKING_REQUEST = 'cancelCheckingRequest'
export const SUBMIT_CHECKING_REQUEST = 'submitCheckingRequest'
export const CANCEL_BOOKING = 'cancelBooking'
export const SUBMIT_BOOKING_REQUEST = 'submitBookingRequest'
export const SUBMIT_FILTER_CHOICE = 'submitFilterChoice'
export const RESET_FILTER_CHOICE = 'resetFilterChoice'
export const LEAVE_SEARCH_RESULT = 'leaveSearchResult'

// Reservation module
export const RESET_ALL_RESERVATION = 'resetAllReservation'
export const GO_NEXT_STEP = 'goNextStep'
export const BACK_PREVIOUS_STEP = 'backPreviousStep'
export const SWITCH_STEP = 'switchStep'
export const INIT_ROOM = 'initRoom'
export const INIT_RESERVATION = 'initReservation'
export const INIT_ON_SEARCH_ROOM = 'initOnSearchRoom'
export const ADD_ANOTHER_ROOM = 'addAnotherRoom'
export const GENERATE_ID = 'generateId'
export const SEARCH_ROOM_TYPE = 'searchRoomType'
export const ADD_ROOM_TO_SELECTION = 'addRoomToSelection'
export const REMOVE_ROOM_FROM_SELECTION = 'removeRoomFromSelection'
export const EDIT_ROOM_FROM_SELECTION = 'editRoomFromSelection'
export const ADD_ADDONS_TO_SELECTION = 'addAddonsToSelection'
export const REMOVE_ADDONS_FROM_SELECTION = 'removeAddonsFromSelection'
export const CALCULATE_TOTAL_AMOUNT = 'calculateTotalAmount'
export const SAVE_ROOM_SELECTION_TO_RESERVATION = 'saveRoomSelectionToReservation'
export const FORWARD_TO_CUSTOMER_INFO = 'forwardToCustomerInfo'
export const ADD_CUSTOMER_DETAILS = 'addCustomerDetails'
export const SAVE_CUSTOMER_INFO_TO_RESERVATION = 'saveCustomerInfoToReservation'
export const FORWARD_TO_CONFIRMATION = 'forwardToConfirmation'
export const SET_CONFIRMATION_NUM = 'setConfirmationNum'
export const SUBMIT_RESERVATION = 'submitReservation'
export const RESET_RESERVED_INFO = 'resetReservedInfo'
export const DISCARD_CHANGES = 'discardChanges'
